
<div class="panel panel-default">
    <div class="panel-heading">Lista de estaciones</div>
    <div class="panel-body">
        <p>
            <button class="btn btn-primary" id="btn-agregar-estacion"><i class="glyphicon glyphicon-plus  "></i> Agregar Estacion</button>
        </p>
<div class ="table-responsive table-bordered" >
     
    <table id="tabla_estaciones" class="table"> 
    <thead>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Tipo</th>
        <th>Habilitado</th>
        <th>Acciones</th>
    </thead>
    <tbody>
        
    </tbody>
</table>
 </div>
    </div>
    <div class="panel-footer">
        <section>
            <strong>Acciones del listado </strong>
        </section>
        
        <section>
            <button class='btn btn-xs'><i class='glyphicon glyphicon-edit'></i></button>
            Editar estación 
            <button class='btn btn-xs'><i class='glyphicon glyphicon-hand-up'></i></button>
            Habilitar estación
            <button class='btn btn-xs'><i class='glyphicon glyphicon-hand-down'></i></button>
            Deshabilitar estación
        </section>
    </div>
</div>

<div id="modal_estacion"></div>