<div class="alert alert-info" role="alert">Seleccione fecha y haga click enel indicador.  Fecha:   <input type="date" disabled="" value="2016-04-20">  </div>
<section>
    
    <div class="row ">
        
        <div class="col-md-3 col-sm-6 " style="margin-bottom: 10px; padding: 15px" >
            <button class="btn btn-lg  col-sm-12" onclick="mostrarGrafico(1)">
                <img src="/assets/img/hot01.png" alt="Conquer">
                <span style="font-size: 0.7em"> Temperatura  </span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px" >
            <button class="btn btn-lg  col-sm-12">
                <img src="/assets/img/clear.png" alt="Conquer">
                <span style="font-size: 0.7em">  Radiacion w/m 8</span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px">
            <button class="btn btn-lg  col-sm-12">
                <img src="/assets/img/cloudywindy.png" alt="Conquer">
                <span style="font-size: 0.7em"> Direccion del viento </span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px">
            <button class="btn btn-lg  col-sm-12">
                <img src="/assets/img/windy.png" alt="Conquer">
                <span style="font-size: 0.7em">Velocidad del viento</span>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-6" style="margin-bottom: 10px; padding: 15px" >
            <button class="btn btn-lg  col-sm-12">
                <img src="/assets/img/freezing.png" alt="Conquer">
                <span style="font-size: 0.7em">  Presion atmosferica</span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px" >
            <button class="btn btn-lg col-sm-12">
                <img src="/assets/img/hazyfreezing.png" alt="Conquer">
                <span style="font-size: 0.7em"> Humedad relativa</span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px">
            <button class="btn btn-lg col-sm-12">
                <img src="/assets/img/flurries.png" alt="Conquer">
                <span style="font-size: 0.7em">Precipitacion </span>
            </button>
        </div>
        <div class="col-md-3 col-sm-6"  style="margin-bottom: 10px; padding: 15px">
            <button class="btn btn-lg  col-sm-12">
                <img src="/assets/img/rain03.png" alt="Conquer">
                <span style="font-size: 0.7em"> Evapotranspiracion</span>
            </button>
        </div>
    </div>
</section>

<section>
    <div class="alert alert-info text-center" role="alert" >Informacion detallada</div>
    
    <div id="contenedor_grafico"></div>
</section>