<div class="col-md-6 col-sm-6">

    <!-- login form -->
    <form action="#" method="post" class="sky-form boxed">
        <header>Iniciar Sesión</header>

        <fieldset>

            <section>
                <label class="input">
                        <i class="icon-append fa fa-envelope"></i>
                        <input required="" type="email" placeholder="Email address">
                        <b class="tooltip tooltip-bottom-right">Needed to verify your account</b>
                </label>
            </section>

            <section>
                <label class="input">
                        <i class="icon-append fa fa-lock"></i>
                        <input required="" type="password" placeholder="Password">
                        <b class="tooltip tooltip-bottom-right">Only latin characters and numbers</b>
                </label>
                <div class="note"><a href="#">Forgot Password?</a></div>
            </section>

            <section>
                    <label class="checkbox"><input type="checkbox" name="checkbox-inline"><i></i>Keep me logged in</label>
            </section>

        </fieldset>
        <footer>
                <button type="submit" class="button">Log in</button>
        </footer>
    </form>
    <!-- /login form -->

</div>
<div class="col-md-6 col-sm-6">
    <p>
        Haz click debajo para iniciar sesión usando:
    </p>
    <p>
        <a href="#" class="btn btn-facebook btn-lg btn-block"><i class="fa fa-facebook"></i> Iniciar Sesión con Facebook</a>
        <a href="#" class="btn btn-google-plus btn-lg btn-block"><i class="fa fa-google-plus"></i> Iniciar Sesión con Google</a>
    </p>
           

</div>