<div class="container" id="fullpage">
    <section>
        <div class="row">
            <div class="col-md-4 " ></div>
            <div class="col-md-4 text-center">

                <h2>Ya tienes cuenta ? </h2>
                <div class="bs-example" data-example-id="button-tag-button-group-justified"> 
                    <div class="btn-group btn-group-justified" role="group" aria-label="Justified button group"> 
                        <div class="btn-group" role="group"> <button type="button" class="btn btn-default scrollTo" href="#contenidoUsuario" onclick="cargaContenido(1)"><i class="glyphicon glyphicon-thumbs-up"></i> SI</button> </div> 
                        <div class="btn-group" role="group"> <button type="button" class="btn btn-default scrollTo" href="#contenidoUsuario" onclick="cargaContenido(2)"><i class="glyphicon glyphicon-thumbs-down"></i> NO</button> </div>
                    </div> 
                </div>

            </div>
            <div class="col-md-4 " ></div>
        </div>
        <div class="row">
            <div id="contenidoRegistro" style="display: none"></div>
            <div id="contenidoLogin" style="display: none"></div>
        </div>
    </section>
</div>