
<div class="panel panel-default">
    <div class="panel-heading">Lista de usuarios</div>
    <div class="panel-body">
<div class ="table-responsive table-bordered" >
     
    <table id="tabla_usuarios" class="table"> 
    <thead>
        <th>Nombre</th>
        <th>Tipo</th>
        <th>Habilitado</th>
        <th>Acciones</th>
    </thead>
    <tbody>
        <?php 
        $usuario = $this->identity();
        
        foreach($this->usuario as $user){
            $nombres = $user->nombres ." ".$user->ap_pat. " " . $user->ap_mat;
            if($user->habilitado == 1){
                $habilitado = "<td><span class='label label-success'>Si</span></td>";
            }else{
                $habilitado = "<td><span class='label label-default'>No</span></td>";
            }
            echo "<tr>";
            echo "<td>$nombres</td>";
            echo "<td>". ($user->rol == 'Administrador')? "<td><span class='label label-danger'>$user->rol</span>":$user->rol  ."</td>";
            echo $habilitado;
            if($usuario["user"]->correo == $user->correo){
                echo "<td></td>";
            }else{
                echo "<td><button class='btn btn-xs'><i class='glyphicon glyphicon-pencil'></i></button> "
                . "&nbsp; <button class='btn btn-xs'><i class='glyphicon glyphicon-list-alt'></i></button> "
                        . "</td>";
            }
            echo "</tr>";
            
            
        }
        ?>
    </tbody>
</table>
 </div>
    </div>
</div>