<div class="col-md-2"></div>
<div class="col-md-8">
<form action="/usuario/login/manual" method="post" class="" id="LoginForm1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Inicia sesíon</div>
                    <div class="panel-body">
                        <div class="col-sm-12 col-md-6">
                        <fieldset>								
                            <div class="form-group">
                                <label class="input">Correo electronico</label>
                                <input name="email" class="form-control" id="email" required="" type="text" placeholder="Correo electronico">
                            </div> 
                            <div class="form-group">
                                <label class="input">Contraseña</label>
                                <input name="password"  class="form-control" id="pass" required="" type="password" placeholder="Contraseña">
                            </div> 
                        </fieldset>
                        <fieldset>
                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="recuerdame" id="recuerdame">  Recuerdame
                                    </label>
                                </div>
                            </div>
                           
                            <div id="captchaContainer2"></div>
                            <div id="captchaMessage2"></div>
                        </fieldset>
                        <fieldset>
                            <div class="form-group">
                                 <button type="submit" class="btn btn-primary" id="registrarBtn">Continuar</button>
                            </div>
                        </fieldset>
                    </div>
                     <div class="col-sm-12 col-md-6">
                         <div class="row">
                        <div class="col-sm-12">
                            Inicia sesion usando : 
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <a  onclick="cargaUrlFacebook('login')" class="btn btn-facebook btn-lg btn-block"><i class="fa fa-facebook"></i> Iniciar Sesión con Facebook</a>
                                <a href="#" class="btn btn-google-plus btn-lg btn-block "><i class="fa fa-google-plus"></i> Iniciar Sesión con Google</a>
                            </div>
                        </div>
                     </div>
                    </div>
                </div>  
            </form>
</div>
<div class="col-md-2"></div>